# .github/workflows/main.yml
name: Django-app workflow

on: [push]

jobs:
  tests:
    # "runner" - creating isolated environment with the latest Ubuntu version
    runs-on: ubuntu-latest

    steps:
    # running actions checkout - ready script
    # for repository cloning
    - uses: actions/checkout@v2
    - name: Set up Python
      # running actions setup-python  -  ready script
      # for repository cloning
      uses: actions/setup-python@v2
      with:
        # Selecting Python version
        python-version: 3.7

    - name: Install dependencies
      run: |
        # updating pip
        python -m pip install --upgrade pip
        # installing flake8 and its plugins
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # installing dependencies
        pip install -r requirements.txt

    - name: Test with flake8 and django tests
      run: |
        # running tests of the project according to flake8
        python -m flake8
        # change dir to folder with manage.py
        #<intra_actions_root_folder>/<project_folder>/manage.py
        cd infra_project/
        python manage.py test

